### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/virtual-each#1]
* [x] Hook up Travis
* [x] Install ember-mocha
* [x] initial render counts
* [ ] rerender counts on scroll position change
* [ ] index is threaded through

**Comment by Robdel12** [comment]
Hey @jasonmit. We're starting to use this and would love to help with wrapping tests around this. Let me know if you have time to coordinate how you'd like to see the tests done/if you have any preferences.

**Comment by jasonmit** [comment]
@Robdel12 awesome.  Just a series of unit tests would suffice for now.

Basics to cover in first pass:
* initial render counts
* rerender counts on scroll position change
* index is threaded through

**Comment by flexyford** [comment]
Hey @jasonmit, @Robdel12 and I are going to start working on these tests :smiley: you should see some PRs coming through in the next few days hopefully

**Comment by flexyford** [comment]
Kicking things off with #5 ember-cli-mocha testing framework
