### ISSUE TITLE
Ember 1.12 Support?

### ISSUE THREAD

**Issue by hadiwina** [jasonmit/virtual-each#105]
Hi! 

Would love to use this library in one of our project, but unfortunately the project is still in Ember 1.12 and we may not be able to upgrade yet at this point due to the complexity of things. 

I'm wondering if there's any list of things from Ember 1.13 that this library requires that I somehow could shim.

Thanks a lot!

**Comment by jasonmit** [comment]
It cannot support < 2.3 because it relies on the contextual component API.

https://emberjs.com/blog/2016/01/15/ember-2-3-released.html#toc_contextual-components

**Comment by hadiwina** [comment]
Thanks for the explanation!
