### ISSUE TITLE
Build Fails for ember#beta

### ISSUE THREAD

**Issue by flexyford** [jasonmit/virtual-each#13]
Any thoughts on ignoring `ember#beta` for our travis build?

**Comment by flexyford** [comment]
It looks like addon components are not properly added to the registry. `A helper named 'virtual-each' could not be found` in the integration tests

**Comment by Robdel12** [comment]
So ember cut a new release yesterday which means new features were turned on in the beta. I think it might have something to do with the new contextual components? http://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_contextual-components

**Comment by jasonmit** [comment]
> Any thoughts on ignoring ember#beta for our travis build?

Remove https://github.com/jasonmit/virtual-each/blob/master/.travis.yml#L15

**Comment by jasonmit** [comment]
Looks like I just had to bump ember-mocha
