### ISSUE TITLE
Enhancement: Option to work with box-sizing property

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#15]
It'd be awesome if this could work out of the box with Bootstrap, which uses `box-sizing: border-box`.

Also, please consider adding the following to the README.md.  I lost a few hours tracking down the conflict between this package's `box-sizing` expectations and Bootstrap.
```
.infinite-list-content {
  ...
  box-sizing: initial;
  -moz-box-sizing: initial;
  -webkit-box-sizing: initial;
}
```

P.S. Awesome addon for Ember!  Appreciate it!

**Comment by jasonmit** [comment]
Send a pr, would happily merge and thanks for the feedback :)
