### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#17]
Using `return this.store.findAll('notes');` in the model, which is making a REST call, I'm seeing this behaviour:

```
template.hbs
{{#virtual-each ... items=model as |item actualIndex virtualIndex|}}
  Nothing displays here
{{/virtual-each}}

{{#each model as |item index|}}
  Display all records in the store
{{/each}}
```

It'd be cool to see support for promises.  In the meantime, do you have any recommendations on how to work around this?

**Comment by jasonmit** [comment]
The goal of the API is to support whatever the each helper supports, so I'm on board with unwrapping promises.  The work around would be creating a helper which unwraps promises.

```hbs
{{#virtual-each items=(unwrap model) as |item actualIndex virtualIndex|}}
 ...
{{/virtual-each}}
```

Untested brain dump that may work:

```js
export default Ember.Helper.extend({
  compute([promise]) {
    const renderedValue = this.get('renderedValue');

    if (renderedValue) {
      return renderedValue;
    }

    Ember.RSVP.cast(promise).then((renderValue) => {
      this.set('renderedValue', renderValue);
      this.recompute();
    });
  }
});
```

**Comment by cowboyd** [comment]
Does `virtual-each` need to be promise aware, or is it as simple as having the rendered slice have a computed dependency somewhere on `items.length`?

**Comment by jasonmit** [comment]
@cowboyd it would need to unwrap the bound promise to determine the length

**Comment by bitsoflogic** [comment]
I haven't been able to test the braindump just yet.

This does not trigger the helper:
```
{{#virtual-each items=(unwrap-promise model) as |item actualIndex virtualIndex|}}
```

This does:
```
{{#each (unwrap-promise model) as |item|}}
```

Using:
ember.debug.js:5378DEBUG: Ember      : 1.13.7
ember.debug.js:5378DEBUG: Ember Data : 1.13.8
ember.debug.js:5378DEBUG: jQuery     : 1.11.3

**Comment by jasonmit** [comment]
> I haven't been able to test the braindump just yet.

I'm not following.. did you or did you not try it? :)

**Comment by bitsoflogic** [comment]
I tried to test it however the helper isn't being called.  I simplified it down to a simple `console.log('hi');` helper and found `(unwrap-promise model)` is only executing with `#each`.  It never fires with `#virtual-each items=(unwrap-promise model)`

**Comment by jasonmit** [comment]
PR opened to resolve this

**Comment by jasonmit** [comment]
0.2.0 resolves this (do not use the unwrap helper, it's not needed).

**Comment by bitsoflogic** [comment]
Thanks for the quick follow-up on this!  I've installed the 0.2.0 release however still cannot get it to work.  

Digging in a bit I found that `Math.max(items.length, 0)` is returning 0.  `{{#each model.notes}}` resolves all records.  The Ember Inspector shows the REST call is fulfilled in both cases.
```
{{#virtual-each 
  itemHeight=71
  height=300
  items=model.notes as |note index|}}
```

My router currently looks like this (backed by the DS.RESTAdapter)
```
  model() {
    return Ember.RSVP.hash({ 
      notes: this.store.query('notes', { status: 'active' }),
      ...
    });
  }
```

**Comment by bitsoflogic** [comment]
I should add that the ultimate goal would be to use this with an `Ember.computed` variable to filter and sort the list.

**Comment by Robdel12** [comment]
I'm interested to see if this has any difference:

```js
 model() {
    notes: this.store.query('notes', { status: 'active' }),
  }
```

**Comment by bitsoflogic** [comment]
This has the same effect. `let items = Ember.A(attrItems);` is `[]`.
```
model() {
  return this.store.query('notes', { status: 'active' })
}
```

`{{#virtual-each itemHeight=71 height=300 items=model as |note index|}}`

**Comment by jasonmit** [comment]
I believe this issue is now different that what was originally asked for.  DS RecordArrays are not just promises.  I'll need to figure out how to support this without coupling virtual each to ember data.

**Comment by bitsoflogic** [comment]
Ah, my apologies for using the wrong terminology earlier.

Should I open a new issue specifically mentioning DS.RecordArrays/Ember.computed, while referencing this ticket?

**Comment by jasonmit** [comment]
Please do and not a problem.  This was needed anyway.
