### ISSUE TITLE
Ember.computed and DS.RecordArrays Support

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#23]
Issue #17 revealed the need for DS.RecordArrays support.  Specifically, it'd be great to use `{{#virtual-each}}` with the following:

```
  model() {
    return Ember.RSVP.hash({
      notes: this.store.query('notes', { status: 'active' })
    });
  }
```

Then add a filter for the UI
```
  filteredNotes: Ember.computed('model.notes.@each...
```

leading to `{{#virtual-each ... items=filteredNotes as |note|}}`

This keeps it in line with mirroring the behavior of `{{#each}}`

**Comment by jasonmit** [comment]
So, we're pretty close to getting this all to work.  I'm kind of too lazy to setup a mocked up ember-data environment, but was able to get ArrayProxy supported which in turn should support DS.RecordArray if all goes as expected.  I've published the changes as 0.2.1, please give it a try.

**Comment by bitsoflogic** [comment]
No change from 0.2.0 for me.

Tested against the filteredNotes, Ember.RSVP.hash, and a simple `model() { return this.store.query...`

**Comment by jasonmit** [comment]
I've tested this against a plain DS.RecordArray and it's rendering it fine on 0.2.1

**Comment by jasonmit** [comment]
Also, feel free to reopen if the issue continues to persist when you use positional params.
