### ISSUE TITLE
DS.RESTAdapter support

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#25]
I know we've been on slightly different pages.  Below outlines my setup and how to reproduce the problem.

I've setup a simple REST endpoint to test against: 
    `http://104.237.151.160:21339/notes?count=50`

- `ember new test-project`
- `cd test-project`
- `npm i virtual-each --save`
- `ember g adapter application`
- `ember g model note`
- `ember g route index`

adapter/application.js
```
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
  host: 'http://104.237.151.160:21339',

  shouldReloadAll() {
    return true;
  }
});
```

model/note.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  body: DS.attr()
});
```

route/index.js
```
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return Ember.RSVP.hash({
      notes: this.store.query('note', { count: 100 })
    });
  }
});
```

templates/index.hbs
```
{{#virtual-each
  itemHeight=18
  height=180
  items=model.notes as |note index|}}
  {{note.body}}
{{/virtual-each}}

<ul>
{{#each model.notes as |note index|}}
  <li>{{note.body}}</li>
{{/each}}
</ul>
```

config/environment.js (Add `contentSecurityPolicy`)
```
... 
  var ENV = {
    ...
    contentSecurityPolicy: {
      'connect-src': "https: http: ws: 'unsafe-inline'",
      'default-src': "https: http: 'unsafe-inline'",
      'script-src' : "https: http: 'unsafe-eval'",
      'style-src'  : "https: http: 'unsafe-inline'",
      'font-src'   : "https: http: 'unsafe-inline'"
    },
... 
```

**Comment by jasonmit** [comment]
Very helpful, thanks for taking the time to set that up.

I've confirmed that it is working.  For whatever reason, in the case of a DS.RecordArray instance, passing `items` as a named attribute initially passes `undefined` and never updates the binding.  I've yet to figure out why, but the work around is to pass it as position param.

`{{#virtual-each items=model.notes ..}}` becomes `{{#virtual-each model.notes ...}}`

Screenshot:

![](http://i.imgur.com/A37lwtc.png)

**Comment by bitsoflogic** [comment]
Ah, excellent!  I see it working now as well... 

Thanks for taking the time to help and for continuing development on this awesome port!
