### ISSUE TITLE
positionIndex cannot return to 0 after it changes

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#26]
Given this, it is not possible to return the list to the top since it is zero-indexed.
```hbs
{{input value=customIndex}}
{{#virtual-each ... positionIndex=customIndex ... }}
```

It looks like `startingIndex` in `scrollTo` just needs to allow for this.  What do you think of this?
```js
  scrollTo(positionIndex) {
    const itemHeight = this.getAttr('itemHeight');
    const totalHeight = get(this, '_totalHeight');
    const _visibleItemCount = get(this, '_visibleItemCount');

   // const startingIndex = Math.max(positionIndex, 0) || get(this, '_startAt');
    var startingIndex = Math.max(positionIndex, 0);
    if (isNaN(startingIndex)) {
      startingIndex = get(this, '_startAt');
    }

    const maxVisibleItemTop = Math.max(0, (get(this, '_items.length') - _visibleItemCount + EXTRA_ROW_PADDING));
    const maxPadding = Math.max(0, totalHeight - ((_visibleItemCount - 1) * itemHeight) + (EXTRA_ROW_PADDING * itemHeight));
    const sanitizedIndex = Math.min( startingIndex, maxVisibleItemTop);
    const sanitizedPadding = (sanitizedIndex === maxVisibleItemTop) ? maxPadding : itemHeight * sanitizedIndex;

    this.calculateVisibleItems(sanitizedIndex);
    this.$().scrollTop(sanitizedPadding);
  },
```

**Comment by jasonmit** [comment]
So your use case is you set it to zero and then scroll, and you want to reset it by setting it to zero again?

**Comment by bitsoflogic** [comment]
Yes.  

The real use-case is that I'm trying to implement an user "Find" to replace the browser's "Find" since the elements aren't actually on the page.  Part of my approach is to programmatically scroll to the index of the matching record, which will be zero sometimes.

**Comment by bitsoflogic** [comment]
I should be able to release a pull request for this tonight or tomorrow.  I'll keep the existing format:

```
//  const startingIndex = Math.max(positionIndex, 0) || get(this, '_startAt');
    const startingIndex = isNaN(positionIndex) ? get(this, '_startAt') : Math.max(positionIndex, 0);
```

On a side note, I found an edge case issue with the `sanitizedPadding` as well that I'll document in another issue when I have more time to explain it...

```
//  const sanitizedPadding = (sanitizedIndex === maxVisibleItemTop) ? maxPadding: itemHeight * sanitizedIndex;
    const sanitizedPadding = (itemHeight * startingIndex > maxPadding) ? maxPadding : itemHeight * startingIndex;
```

**Comment by flexyford** [comment]
:+1:  LGTM Thanks for including me in this issue. It's true that setting this to zero did not work. Please include  test  on https://github.com/jasonmit/virtual-each/blob/master/tests/unit/virtual-each-test.js#L213

should look something pretty similar to the code below
```javascript
      describe("re-positioning to the first item", function() {
        beforeEach(function() {
          run(() => {
            this.set('positionIndex', 0);
          });
        });

        it("rerenders with the first item at the top", function() {
          var $component = this.$('.virtual-each');
          expect($component.find('li').first().text()).to.contain('Item 0);
        });
      });
```

**Comment by bitsoflogic** [comment]
***Need some help here***
I'm fairly new to Ember and this is my first stab with PhantomJS, so my apologies in advance if I'm missing something obvious here.  I cannot quite figure out how `scrollTo` is being triggered by `positionIndex` changing.  Is Ember.js firing a new `didReceiveAttrs`, which in turn schedules another `afterRender` event?

***Where I'm at***
The last two tests in the suite do a `this.set('positionIndex', undefined)`, which is converted to `0` before hitting the `scrollTo(...)` and `calculateVisibleItems(...)` methods.  I'm trying to figure out how to preserve the `undefined` value, or do something similar so that we don't scroll the list on `undefined`.

***The nitty gritty***
I modified the test slightly:
```
      describe("re-positioning to the first item", function() {
        beforeEach(function() {
          run(() => {
            this.set('positionIndex', 10);   // Move it elsewhere on the list, then back
            this.set('positionIndex', 0);
          });
        });

        it("rerenders with the first item at the top", function() {
          var $component = this.$('.virtual-each');
          expect($component.find('li').first().text()).to.contain('Item 0');
        });
      });
```

The following code fixes this, but breaks the last two tests, each of which do `this.set('positionIndex', undefined)` since these methods see these calls the same as `this.set('positionIndex', 0)`
```
// In calculateVisibleItems(...) 
const visibleStart = isNaN(positionIndex) ? Math.floor(scrolledAmount / ... ) : positionIndex;

// In scrollTo(...)
const startingIndex = isNaN(positionIndex) ? get(this, '_startAt') : Math.max(positionIndex, 0);
```

**Comment by flexyford** [comment]
I'm not sure, but it might have something to do with `defaultAttrs`:
```
defaultAttrs: {
    positionIndex: 0,
    scrollTimeout: 30,
    height: 200,
    itemHeight: 20
  },
```

**Comment by bitsoflogic** [comment]
So, I found that `afterRender` is the source of the conversion from `undefined` to `0`:

```
        emberRun.scheduleOnce('afterRender', () => {
          console.log('afterRender: ' + this.getAttr('positionIndex'));
          if (typeof attrs.oldAttrs !== 'undefined') {
            console.log('afterRender direct old: ' + attrs.oldAttrs.positionIndex.value); 
            console.log('afterRender direct new: ' + attrs.newAttrs.positionIndex.value); 
          }
          console.log('------------- ');
          this.scrollTo(this.getAttr('positionIndex'));
        });
```

When the test sets to `undefined`, this shows the following:
```
            afterRender: 0
            afterRender direct old: 200
            afterRender direct new: undefined
```

I'm not sure why `this.getAttr('positionIndex')` is reporting `0` just yet.

**Comment by flexyford** [comment]
We are importing a ```import DefaultAttrsMixin from '../mixins/default-attrs';``` so try a default of `undefined` and see if tests are passing

**Comment by bitsoflogic** [comment]
Thanks for the notes @flexyford.  

With the current code, `undefined` and `0` have the same behavior, so I'd assume they'd pass without my change.  Nevertheless, I'll look into that as well.

**Comment by bitsoflogic** [comment]
Weird... I just found `this.get` to preserve the `undefined`, while `this.getAttr` does not.

Just want to be sure this change is okay:
```
emberRun.scheduleOnce('afterRender', () => {
  this.scrollTo(this.get('positionIndex')); // this.getAttr changed to this.get
});
```
No conflicts with Ember deprecations?  This passes all tests on my ember version 1.13.13.

**Comment by flexyford** [comment]
Did you try 
```
defaultAttrs: {
    positionIndex: undefined,
    scrollTimeout: 30,
    height: 200,
    itemHeight: 20
  },
```
I think this would allow us to keep this.getAttr('positionIndex')

**Comment by bitsoflogic** [comment]
That works as well!  I was rushing out and just made one last attempt.  It didn't quite click what you were referring to when you mentioned the Mixin.  Sorry about that.  Looking closer, I see `getAttr` is a custom method in that Mixin! Great call!

My thought is to just remove `positionIndex` from the object, since it isn't being defaulted to anything at that point.  This also passes all tests.  Any reason to keep it?
