### ISSUE TITLE
scrollTo prefers keeping the last item fully visible over the scrolled to item

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#27]
Given 2.5 records fit in the display, the list is 10 long, and you set `positionIndex = 8`, you'll get this:
```
|-------
| Item 8 // Top half is cut off, despite attempting to scroll to it.
|
|-------
|
| Item 9
|
|-------
| 
| Item 10 // Last item
| 
|-------
```

Expected behaviour on `positionIndex = 8`:
```
|-------
|
| Item 8 
|
|-------
|
| Item 9
|
|-------
| 
| Item 10 // Last item (partially cut off, since you're scrolling to 8)
|-------
```

This was my idea for a fix however I need to vet it against the test suite still:
```
//  const sanitizedPadding = (sanitizedIndex === maxVisibleItemTop) ? maxPadding: itemHeight * sanitizedIndex;
    const sanitizedPadding = (itemHeight * startingIndex > maxPadding) ? maxPadding : itemHeight * startingIndex;
```

For the test assertion, I'm guessing it would be best to assert the `scrollTop` position.  What do you think?

**Comment by flexyford** [comment]
I believe this solution ignores the ```const EXTRA_ROW_PADDING = 1;```

**Comment by flexyford** [comment]
You are right though, the expected behavior is to bind to the top of item 8

**Comment by bitsoflogic** [comment]
The `EXTRA_ROW_PADDING` is calculated in maxPadding, so it's still used in the cases where it's hitting the end of the list.  For all the rows leading up to it there doesn't appear to be any difference in index calculation with or without it.  

That being said, we can't use `itemHeight * sanitizedIndex > maxPadding` as that will never be true.

The problem I'm encountering atm is an off-by-one issue:
```
  // positionIndex = 185
  const sanitizedPadding = (itemHeight * startingIndex > maxPadding) ? maxPadding : itemHeight * startingIndex;
  // santizedPadding = 6475
  // Test reports $component.scrollTop() === 6474

  // If i change the padding by 1, scrollTop() changes by 2...
  const sanitizedPadding = (itemHeight * startingIndex > maxPadding) ? maxPadding : itemHeight * startingIndex + EXTRA_ROW_PADDING;
  // santizedPadding = 6476
  // Test reports $component.scrollTop() === 6476
```

Having gone through more tests, it looks like `scrollTop` is moving in increments of 2 pixels.

**Comment by bitsoflogic** [comment]
If you don't object, I'm going to commit with this test:
```
      describe("positioning where the last item is in view", function() {
        beforeEach(function() {
          run(() => {
            this.set('positionIndex', 185);
          });
        });

        it("sets the scrollTop such that the first item shown is not cutoff", function() {
          var $component = this.$('.virtual-each');
          let firstVisibleItem = 185;
          let itemHeight = 35;
          expect($component.scrollTop()).to.be.closeTo(firstVisibleItem * itemHeight, 1);
        });
      });
```

I still have the fix as: 
```
  const sanitizedPadding = (itemHeight * startingIndex > maxPadding) ? maxPadding : itemHeight * startingIndex;
```

All tests pass with those changes.

**Comment by flexyford** [comment]
will have to look into this a bit later

**Comment by flexyford** [comment]
This looks good to me. Can we make it a bit more clear?
```
const startingPadding = itemHeight * startingIndex;
const sanitizedPadding = (padding > maxPadding) ? maxPadding : startingPadding;
```
