### ISSUE TITLE
Need to persist ScrollTop()

### ISSUE THREAD

**Issue by flexyford** [jasonmit/virtual-each#31]
I've noticed an issue of persisting the scrollTop when a new `items` array is passed in. 

The scrollTop `resets` to the beginning of the `_startAt`, when what we REALLY want is to persist the `scrollTop` at the current pixel. So right now we have "index-persistance" but not "scrollTop-persistance" when receiving a new items array. 

This appears as a glitch in cases where we have scrolled part-way through an item:

Let's say we are looking at an `Item 8`, but have scrolled part-way through it . . . 

|-------
| Item 8 // Top half is cut off. Looking good!
|
|-------
|
| Item 9
|
|-------
| 
| Item 10 // Last item
| 
|-------

Let's say scrollBottomed, and we receive more items in our items array. We would expect the scrollTop to remain at the current pixel, but it instead resets to the beginning of the current item index:

|-------
|
| Item 8 // Top half is exposed, which is not the desired UI. Looking glitchy!
|
|-------
|
| Item 9
|
|-------
| 
| Item 10 // Last item
| 
|-------

I will try and work on a solution for this. But I think it has to do with calling `caculateVisibleItems(positionIndex)` whenever we receive an new items array. Perhaps this is not the desired logic when receiving a new items array?

**Comment by jasonmit** [comment]
> The scrollTop resets to the beginning of the _startAt, when what we REALLY want is to persist the scrollTop at the current pixel

Completely agree
