### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#33]
@jasonmit Hey, would you shoot out a new `npm version` to reflect the latest changes?  My project requires the same changes @flexyford just released on #32 and I'd like to lock to a specific release.

Thanks!

**Comment by Robdel12** [comment]
I just cut a new version :) https://github.com/jasonmit/virtual-each/commit/360bd07b84570647b14bbedc693a7ace75650a64
