### ISSUE TITLE
Feature: Executing an action onscroll

### ISSUE THREAD

**Issue by bitsoflogic** [jasonmit/virtual-each#39]
Hey,

I have an `ember-xselect` component within {{#virtual-each}} that isn't resetting the display when the user scrolls to different rows.  It resets under the hood, so the value submitted isn't what is currently displayed for the user.

To resolve this, I'd like to tie a `resetSelects` action to virtual-each onscroll.  I'd like to submit this as a PR.  Let me know if anything should be changed, or if this solution is just a bad idea for whatever reason...

The lines with `onScrolling` are the only new additions/changes:
```
  eventHandlers: {
    wheel() {
      this._scrolledByWheel = true;
    },

    scroll(e) {
      e.preventDefault();

      const scrollTimeout = this.getAttr('scrollTimeout');
      const onScrolling = this.getAttr('onScroll');

      if (scrollTimeout && this.isWebkit && this._scrolledByWheel) {
        this._scrolledByWheel = false;

        if (!this._scrollTimer) {
          this._scrollTimer = setTimeout(() => {
            this._scrollTimer = null;
            this.calculateVisibleItems();
          }, scrollTimeout);
        }

        if (typeof onScrolling === 'function') {
          onScrolling();
        }
        return;
      }

      this.calculateVisibleItems();

      if (typeof onScrolling === 'function') {
        onScrolling();
      }
    }
  },
```

This allows:
```

{{#virtual-each
  filteredNotes
  itemHeight=73
  height=virtualEachHeight
  onScroll=(action "resetSelects")
  positionIndex=currentFindIndex as |note index|}}
```

In the component... 
```
  resetSelects: function() {
    Ember.$('select').each(function() { this.selectedIndex = 0; });
  },
```

**Comment by Robdel12** [comment]
Hm, this sounds like an x-select issue. What do you mean by:

> It resets under the hood, so the value submitted isn't what is currently displayed for the user.

Do you mean `x-select` is resetting the value within the component but it isn't showing the change in the DOM?

**Comment by bitsoflogic** [comment]
Yeah, it's hard to describe.

Virtual-each is reusing the select element for other rows, but not updating the select fully.  To clarify (hopefully), here's a few use cases of the bug:

Scenario One
1. Row A's select is changed from "Choose State..." to "Delaware"
2. Clicking submit will trigger the back-end to see "Delaware" 
3. Woot! It worked.

Scenario Two
1. Row A's select is changed from "Choose State..." to "Delaware"
2. User scrolls to Row Z, which happens to occupy the same virtual row Row A used to
3. At this point, Row Z displays "Delaware"
4. Clicking submit will trigger the back-end to see "Choose State..."
5. Aww.. Ideally Row Z would have displayed "Choose State...", since the user didn't change it.

While virtual-each properly replaces out <textarea> and other fields, the <select> isn't updated as would be expected.

**Comment by bitsoflogic** [comment]
So, after thinking on your comment more and re-reading my explanation, I couldn't help but agree this was likely not on your end.  This morning I learned ember-power-select and it's working perfectly.

Thanks for taking the time to point me in the right direction!

**Comment by Robdel12** [comment]
Just make sure you don't have any accessibility needs if you're using a select replacement.

**Comment by bitsoflogic** [comment]
Wow.  I didn't even realize it wasn't a select under the hood!  Great call on that.  I'm fine in my current application, but will need to be mindful of it in the future for sure.  What do you use for selects with virtual-each with accessibility needs in mind?

**Comment by Robdel12** [comment]
I'd use a native select if possible. I still think the bug lies with x-select, which I maintain :) 

I'll have some time this weekend I think to try and reproduce & fix

**Comment by bitsoflogic** [comment]
Just to help with reproducing it, here's a few more details.  Thanks again for your help.

In the template:
```
          {{#x-select action="prepareToReset" note=note class="pull-right"}}
            <option value="">Reset to...</option>
            {{#each possiblePlatforms as |platform|}}
              {{#x-option value=platform}}{{platform}}{{/x-option}}
            {{/each}}
          {{/x-select}}
```

In the component:
```
actions: {
    prepareToReset: function(selection, component) {
      component.get('note').set('selectedPlatform', selection);
    },
```

Then, when hitting `submit`, I could read the `note.selectedPlatform`.
