### ISSUE TITLE
Make extra row padding an attribute

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/virtual-each#6]
Right now a constant.. I could see if you'd dealing with images a larger padding would be needed.

**Comment by flexyford** [comment]
EXTRA_ROW_PADDING exists for the case when the `item_height` does not divide evenly into the `height`. I find that in some cases, when we scroll to the bottom, we scroll post the final item revealing empty space. EXTRA_ROW_PADDING solves the padding issue, but only for cases where
```js
(height % item_height >= 0.5 * item_height)
```
but not the case where 
```js
(height % item_height < 0.5 * item_height)
```

I will create a test for this soon, but EXTRA_ROW_PADDING as an attribute would still not resolve this issue.

**Comment by jasonmit** [comment]
Ah, glanced at it and thought I wasn't exposing part of the api.

**Comment by jasonmit** [comment]
But yes, please create an issue if you're seeing what you described.
